name: deploy-expiration
on:
  push:
    branches:
      - master
    paths:
      - "expiration/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t sarthakjha/expiration .
      # logging into docker and pushing image
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push sarthakjha/expiration
      # installing doctl to update the cluster
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DO_ACCESS_TOKEN}}
      # giving cluster connection context to rollout update
      - run: doctl kubernetes cluster kubeconfig save k8s-ticketing
        # rolling out new expiration deploymemt
      - run: kubectl rollout restart deployment expiration-depl
